# Generated by Django 4.2.4 on 2023-09-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitems',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
